### PR TITLE
add gekko usb miner

### PR DESCRIPTION
**Pull request by jameshilliard**
untested

### CODE REVIEW

**Comment by kanoi** [comment]
It's an addition to the icarus code, not a replacement.
So it's not supposed to be a whole new module.

**Comment by jameshilliard** [comment]
Yeah, I figured I would get a diff up at least and hopefully figure out what parts are actually changed.

**Comment by kanoi** [comment]
It wouldn't be pulled in as a duplicate like it is, but even if it was, the configure would need to explicitly exclude being able to include icarus and gekko since gekko will conflict with icarus (gekko is simply icarus + gekko combined into a new module) and cgminer won't even compile with both icarus and gekko due to that

**Comment by kanoi** [comment]
https://github.com/ckolivas/cgminer/pull/695

**Pull request closed without merging**
