### PR TITLE
Bip9 rules support and Segwit commitment insertion

### PR DESCRIPTION
**Pull request by theuni**
Similar to the ckpool PR.

Only solo support is added here, as I'm not sure what to do about the missing txids otherwise. Tested a good bit on testnet.

There seems to be a race condition that causes merkle mismatches sometimes, but I was able to reproduce that with the current cgminer master on mainnet (with a force-reduced difficulty), so I'm confident that it's unrelated.

### CODE REVIEW

**Comment by kanoi** [comment]
Should be off by default and on by an option

**Comment by theuni** [comment]
It abides by the gbt logic. If the server forces the segwit rule, that means that insertion is necessary in order to produce a valid block.

To "turn it off", one should use a btcd that does not include witness txs, and therefore does not enable the segwit rule.

**Comment by kanoi** [comment]
"advertise segwit support for solo mining" <- this clearly is not mandatory for cgminer to work
... and already stating that you've seen a race condition would also mean enabling possibly buggy code by default would be a bad idea.

**Comment by theuni** [comment]
The race condition currently exists on master, it happens when simply solo mining on testnet. I only mentioned it as I thought someone might run into it while testing, and blame it on the changes here.

It will be necessary once segwit activates. At that point, gbt will refuse to send a template unless support is advertised. Again, that is visible at the moment on testnet, where cgminer is essentially only able to mine empty blocks.

**Comment by kanoi** [comment]
Sounds like a major flaw in the segwit implementation if all blocks must contain segwit data, and no transaction are allowed in a block without segwit data ... hopefully they'll fix that soon ...

**Comment by theuni** [comment]
There can be blocks without witness data, but bitcoind does not attempt that. Someone may create a version that filters them out and does not enable the segwit rule, and cgminer would avoid inserting appropriately.

**Comment by ckolivas** [comment]
Merged with minor changes, thanks.

**Pull request merged**
