### PR TITLE
Added GekkoScience Compac detection and support to the icarus driver.

### PR DESCRIPTION
**Pull request by vthoang**
Moved in the relevant portions from the gekko version, minus the ramp up code. It looks to be able to pick up my compac, mine, and is behaving normally.   I don't have a spare icarus compatible device laying around to regress or multi-device test.

### CODE REVIEW

**Comment by jameshilliard** [comment]
You can probably put the additional frequencies for compacfreqtable under u3freqtable and just use that, AFAIK the conversion is the same for both devices.

**Comment by jameshilliard** [comment]
Tested on U3 and doesn't appear to cause regressions with that device, I don't have a compac for multi-device testing but it at least doesn't break the U3 by itself.

**Comment by vthoang** [comment]
Initially tried one frequency table, but then noticed a handful of extra frequencies not found in the U3 user guide, tucked in the U3's range.
Enough of a difference to introduce an anomaly / risk.   
Took the safer route to keep that separate as a unique property for each to minimize change to existing working code.

**Comment by kanoi** [comment]
I'm not sure who thinks it would be a good idea to pull code in not tested properly, but since no one has multiple devices to test it, I'm certainly not going to merge it.
I hear these miners are worth a few million dollars, so yeah I guess sending us one to be able to actually test it before including the code in master cgminer is gonna blow anyone's budget.

**Comment by jameshilliard** [comment]
@vthoang maybe make a post on the compac bitcointalk thread and ask someone with one and a U3 or other icarus based device like a rockminer to test them together

**Comment by vthoang** [comment]
Keeping it as it's own driver seemed redundant, keeping them together has its own challenges.   But still seems like the better route to not have redundant code.   I'll ping the forum.   But if there is an us address for the gekkoscience team to send a spare one to, let me know, i'll trace down a way to get a compac to you.   Seeing this in the main would be nice.

**Comment by jameshilliard** [comment]
@vthoang yeah, keeping them together is def how you want to do it since it's so similar to other icarus style devices, I think gekkoscience has some other icarus devices so you might be able to get them to test this, kanoi and ckolivas are both in australia unfortunately so sending them hardware can sometimes be expensive shipping wise but would be ideal if possible

**Comment by kanoi** [comment]
It wasn't it's own driver before.

**Comment by jameshilliard** [comment]
@kanoi I think theirs was separated out into driver-gekko.c

**Comment by vthoang** [comment]
gekkoscience group only have one device of this class, which is a BM1384 (pulled?) chip turn into a lightweight usb stick miner.   it can use the same icarus (U3) logic to drive it.

**Comment by kanoi** [comment]
The U3 is the worst designed and implemented 'recent' miner that we support.
Doesn't sound too convincing about how good the gekko miner is ...

**Comment by vthoang** [comment]
i believe it's a pure coincidence.  it "can" use the logic because it uses the same manufacturer asic chip (messaging format) and has a usb interface.   i think that the end of the similarity.  you can probably give it a better assessment if there was one handy for you to examine.

**Comment by vthoang** [comment]
@kanoi, new to github, so bear with me i'm doing this incorrectly at first.  which it looks like i may be to some extent.   the feedback is great.   hoping to contribute to the code, not introduce something to lower the quality of the code.  also working to see if i can get a unit your way in the process.

**Comment by vthoang** [comment]
At this last commit (70cac0d).   Locally tested with compac, working as expected.   Also got confirmation from device maker via bitcointalk that it works with multi-unit compac + icarus based non-compacs: "Initialized the Bitshopper stick, 8x Compacs ranging from PCB version 0.4 (initially distributed test sticks), 0.5 (first production run) and 0.6 (second production run) plus a Bitmain U2 and a NanoFury 6 (--enable-bitfury) no problem, everything's running."

**Comment by hrobeers** [comment]
The miner supports frequencies as low as 100MHz instead of 125MHz.
This works for me (but didn't check if really operating at 100MHz):  https://github.com/hrobeers/cgminer-ppc/commit/625ffd79be617cab2c4a6ee0ebadb595372e1c78

**Pull request merged**
